# permissions for end users to view serviceentries.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: serviceentry-viewer-role
rules:
- apiGroups:
  - networking.aspenmesh.io
  resources:
  - serviceentries
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.aspenmesh.io
  resources:
  - serviceentries/status
  verbs:
  - get
